from accept_solution import *
from add_problem import *
from add_solution import *
from problems.views.post_user_unblock import *
from problems.views.post_user_ignore import *
from outdated_problems import *
from problems.views.post_ratings import *
from register import *
from user_authentication import *
from edit_solution import *
from problems.views.check_the_unchecked_notifications import *
from problems.views.get_notifications import *
from problems.views.get_problems import *
from problems.views.tag_cloud import *
from problems.views.get_problems_by_tag import *
from problems.views.get_user_details import *
from problems.views.get_problems_by_keyword import *
from problems.views.get_users_by_keyword import *
from problems.views.get_ignored_users import *
from problems.views.get_ratings import *
from problems.views.own_problems import *
from problems.views.edit_problem import *